Add Lithuanian translation
maunium/dontasktoask.com pull request #120
Opened 2023-02-20 17:06 UTC by DINKONDBD

I am translated whole site to Lithuanian language

2023-02-27 11:29 UTC, tulir commented on lt/index.html
> +  <meta property="og:url" content="https://dontasktoask.com/ru/" />
```suggestion
  <meta property="og:url" content="https://dontasktoask.com/lt/" />

```

2023-02-27 11:29 UTC, tulir commented on lt/index.html
> +    -
These look unnecessary

```suggestion
```

2023-02-27 11:29 UTC, tulir commented on lt/index.html
> +  </footer>
You can add translation credits to the footer and/or readme if you want

2023-11-19 18:17 UTC, TruncatedDinoSour requested changes
please fix the translation :)

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +    </p>
take punctuation into consideration

and this shifts the meaning of the sentence a bit

replace 'tinkamoje' w 'tam tikroje, as 'tinkamoje' sounds a bit weird here

'klausiate apie daugiau' shifts the meaning of the sentence, the sentence should b like 'prašote daug daugiau nei manote' or smt like tht

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +	nes atsakymai yra tik sveikas protas (programuotojo požiūriu).
another place where ur mixing 'klausiate' and 'prašote', which shifts the meaning of the sentence

plus ur using incorrect pronouns and gendering ( e.g. Tu abejoja => Tu abejoji )

this sentence should b re-translated, idk if theres a proper word for libraries but my old informatics teacher used to call it 'biblioteka' so idk, feel free to find a better word :

> Jūs prašote žmonių prisiimti atsakomybę. Jūs keliate abejonių dėl žmonių gebėjimų. Jūs taip pat nereikalingai atskiriate kitus žmones. Dažnai atsakau į klausimus, susijusius su programavimo kalbomis ar bibliotekomis, kurių niekada nenaudojau, nes atsakymai (programuotojo požiūriu) yra visiems žinomi.

kinda a botched translation bc its hard to translate this properly

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +		kas galėtų į tai atsakyti.
sounds a bit weird w 'tai', try using 'jį' instead

smt like 'nebent čia yra kažkas, kas galėtų jį atsakyti'

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +		turėtume to norėti?
this sentence also looks very weird and odd, i cant even make sense out of it rlly lol

instead, u should say smt like : 

> ... o tai tiesiog tingu. Jei nenorite atlikti darbo, kad išspręstumėte savo problemą, kodėl turėtume tai padaryti mes?

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +		tačiau jūsų tikrosios problemos aprašymas gali sukelti jų susidomėjimą ir priversti juos atsakyti.
should b re-translated as this makes no sense, heres the original sentence : 

> The solution is not to ask to ask, but just to ask. Someone who is idling on the channel and only every now and then glances what's going on is unlikely to answer to your "asking to ask" question, but your actual problem description may pique their interest and get them to answer.

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +      <em>"kaip padaryti [problema] naudojant Java kalba, ir [kita atitinkančia informacija]?"</em>
maybe instead of 'padaryti' this should b like 'atlikti' or 'išspręsti'

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +      Susiję klausimai: <a href="https://xyproblem.info/">XY problema</a>, <a href="https://nohello.net/">Ne labas</a>.
'ne labas' lmao

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +      arba jeigu jus turite daug laiko: <a href="http://catb.org/~esr/faqs/smart-questions.html">Kaip klausti klausimą protingas būdas</a>.
'Kaip protingau klausti klausimą' would b correct, this just looks weird xD

2023-11-19 18:17 UTC, TruncatedDinoSour commented on lt/index.html
> +    Kontentas daugiausiai paimtas iš <a href="https://iki.fi/sol/dontask.html">iki.fi/sol/dontask.html</a>
turinys, not kontentas

2023-11-20 19:24 UTC, closed without merging

2023-11-20 20:37 UTC, TruncatedDinoSour commented
sad