Improve Korean translation
maunium/dontasktoask.com pull request #69
Opened 2021-10-31 15:20 UTC by dp0973

2021-10-31 15:38 UTC, ombe1229 commented on ko/index.html
> +        어떤 문제라도, 심지어 자바에 관련되어 있지도 않거나
```suggestion
        이 문제가 어떤 문제일지라도, 심지어 자바에 관련되어 있지도 않거나
```

2021-10-31 15:41 UTC, ombe1229 requested changes

2021-10-31 15:41 UTC, ombe1229 commented on ko/index.html
> +      그 문제를 해결할 지식을 가진 사람들이 답변하는 것을 거부하는 데에는 많은 이유가 있습니다.
```suggestion
      그 문제를 해결할 지식을 가졌음에도 그 사람들이 답변하는 것을 거부하는 데에는 많은 이유가 있습니다.
```

2021-10-31 15:41 UTC, ombe1229 commented on ko/index.html
> +      그렇게 물어본다면 당신은 당신이 묻는다고 생각하는 것보다 더 많은 지식을 요구하고 있는
```suggestion
      위와 같이 물어본다면 당신은 당신이 묻는다고 생각하는 것보다 더 많은 지식을 요구하고 있는
```

2021-10-31 15:41 UTC, ombe1229 commented on ko/index.html
> +      프로그래밍 언어나 라이브러리에 관한 질문을 답하곤 합니다. 답변이 (프로그래머에게 어느정도는)
```suggestion
      프로그래밍 언어나 라이브러리에 관한 질문을 답하곤 합니다. 그 답변이 (프로그래머에게 어느 정도는)
```

2021-10-31 15:41 UTC, ombe1229 commented on ko/index.html
> +      왜 우리는 그래야 하죠?
```suggestion
      우리가 왜 답변을 해 줘야 하죠?
```

2021-11-12 20:16 UTC, revi commented
line-break가 인위적으로 잘린 이유가 있나요? 라인 맞추시려는 이유면 스타일시트에 keep-all 추가해도 될 것 같은데요.

([Word-break: keep-all;](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) 하러 왔다가 패치 보이길래요...)

2021-11-12 20:20 UTC, revi requested changes

2021-11-12 20:20 UTC, revi commented on ko/index.html
> +      해법은, 질문을 위한 질문을 던지지 말고 그냥 질문을 하는 겁니다. 채널에서 조용하고
> 채널에서 조용하고 무슨 일이 생겼는지 가끔 눈팅이나 하는 사람ㅇ느

보다는...

> 채널에 자주 들어오지 않고 가끔 기웃거리기만 하는 사람들

또는 그런 요지로 바꾸는 건 어떨까요?

2021-11-12 20:20 UTC, revi commented on ko/index.html
> +    <a href="https://github.com/maunium/dontasktoask.com">GitHub 자료</a>
Source Code의 Source이기 때문에 "자료"보다는 음차를 했습니다.

다른 대안이 있으시면 그것도 좋겠지만 자료는 적절치 않은 번역 같습니다.

2022-02-04 22:49 UTC, revi commented
(^ wrong click)

답이 없으셔서 PR은 닫습니다.

2022-02-04 22:49 UTC, closed without merging