Brazilian Portuguese translation
maunium/dontasktoask.com pull request #78
Opened 2021-11-25 20:12 UTC by danarrib

This is Brazilian Portuguese translations. 
It's better than the previous submitted ones (#9, #41 and #63) as it:

- Does not include any extra "credits".
- It's perfect 1:1 content, meaning and context match from the original version.
- HTML headers are correctly changed to match pt-BR locale.

Hope you enjoy.

2021-11-26 11:25 UTC, rffontenelle requested changes
Thanks for the PR 🇧🇷. I found some simple typos. Could you please fix them?

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +        Alguém que entende de Java por ai?
ai -> aí

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +        Alguém por ai que entende está disposto a se comprometer a olhar o meu
ai -> aí

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +      Existem várias razões pelas quais as pessoas que TEM o conhecimento
TEM -> TÊM

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +      não admiritiam que tem. E ao perguntar, você está pedindo por mais do que
admiritiam -> admitiriam

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +        Eu tenho uma dúvida sobre Java mas eu sou muito preguiçoso para formalizar
Comma before "mas" (, mas)

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +        responde-la
respondê-la

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +      <em>"Alguém que conhece de Java por ai?"</em>,
ai -> aí

2021-11-26 11:25 UTC, rffontenelle commented on pt-br/index.html
> +    <a href="https://github.com/maunium/dontasktoask.com">Código fonte no GitHub</a>
Código-fonte

2021-11-26 14:36 UTC, danarrib commented
> Thanks for the PR 🇧🇷. I found some simple typos. Could you please fix them?

Fixed. Thanks for the heads up!

2021-11-26 14:39 UTC, rffontenelle approved these changes

2021-11-26 14:39 UTC, rffontenelle commented
LGTM

2021-11-28 18:31 UTC, tulir approved these changes
Thanks for sorting that out, I'll merge this quickly before there are more duplicates :D

2021-11-28 18:31 UTC, merged