Add meta og:description
maunium/dontasktoask.com pull request #96
Opened 2022-04-02 14:39 UTC by wyzlle

2022-04-20 04:33 UTC, yusufmalikul commented
Any chance to review this? @tulir

2022-04-21 05:12 UTC, revi commented
Personally it'd be much better to say something in line of "don't poke around to see someone, just ask your question in full right away" than just Java reference - I often use this page in non-programming environments and it'd be bit confusing in such cases.

2022-05-07 19:41 UTC, mtatko commented
> Personally it'd be much better to say something in line of "don't poke around to see someone, just ask your question in full right away"

I have to agree with this one. The Java reference is there as an example of good and bad questions and might be confusing if you use the website in non-programming related discussion. The og:description should be something that makes a person immidiately think "oop, I should do this next time, instead of doing that".

2022-05-07 19:42 UTC, mtatko requested changes
> Personally it'd be much better to say something in line of "don't poke around to see someone, just ask your question in full right away"

I have to agree with this one. The Java reference is there as an example of good and bad questions and might be confusing if you use the website in non-programming related discussion. The og:description should be something that makes a person immidiately think "oop, I should do this next time, instead of doing that".

2022-05-13 18:57 UTC, mtatko commented on index.html
> +  <meta property="og:description" content="Ask your questions directly instead of asking to ask. />
What about something in line of `Hey, you! Don't poke around to see someone, ask your question in full right away. Thanks!`? In my opinion that seems way better than going full passive-agressive with "ask directly, don't ask to ask", however I'd love to hear what others think of that. I'm going to leave this as a comment for now.

2022-05-13 18:57 UTC, mtatko commented on index.html
> +  <meta property="og:description" content="Ask your questions directly instead of asking to ask. />
@revi what do you think?

2022-05-24 08:45 UTC, mtatko approved these changes

2022-09-19 08:23 UTC, closed without merging